name: Build & Release App

# 触发条件：手动触发或标签推送
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      # 作业级环境变量（整个作业有效）
      m7a_another: ${{ github.repository_owner }}
      m7a_repo: ${{ github.event.repository.name }}
    steps:
      # 步骤1：签出代码
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: "false"

      # 步骤2：设置Python环境
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      # 步骤8.1：下载上一个正式 release 的 March7thAssistant_full.zip 并解压
      - name: Get previous release tag
        id: prev_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/github-script@v7
        with:
          script: |
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 5
            });
            // 当前tag
            const currentTag = context.ref.replace('refs/tags/', '');
            // 找到上一个正式release（非prerelease，且tag小于当前tag）
            let found = false;
            let prev = null;
            for (const rel of releases) {
              if (rel.tag_name === currentTag) {
                found = true;
                continue;
              }
              if (found && !rel.prerelease) {
                prev = rel;
                break;
              }
            }
            if (!prev) {
              core.setOutput('url', '');
              core.setOutput('tag', '');
            } else {
              // 查找附件
              const asset = prev.assets.find(a => a.name === 'March7thAssistant_full.zip');
              core.setOutput('url', asset ? asset.browser_download_url : '');
              core.setOutput('tag', prev.tag_name);
            }

      - name: Download previous release full zip
        if: startsWith(github.ref, 'refs/tags/') && steps.prev_release.outputs.url != ''
        run: |
          mkdir ./dist/prev_release/
          curl -L "${{ steps.prev_release.outputs.url }}" -o ./dist/prev_release/March7thAssistant_full.zip

      - name: Unzip previous release
        if: startsWith(github.ref, 'refs/tags/') && steps.prev_release.outputs.url != ''
        run: |
          mkdir ./dist/prev_release/unzip
          7z x ./dist/prev_release/March7thAssistant_full.zip -odist/prev_release/unzip

      # 步骤3：安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller==6.14.1

      # 步骤4：生成程序
      - name: Generate program
        run: |
          pyinstaller -D --distpath .\dist\ -i .\assets\logo\Terminal.ico --contents-directory libraries --exclude-module PyQt5 --uac-admin -n "March7th Assistant" main.py -y
          pyinstaller -D --distpath .\dist\ -i .\assets\logo\March7th.ico --contents-directory libraries --uac-admin -n "March7th Launcher" app.py -y -w
          pyinstaller -F --distpath .\dist\March7thAssistant\ -i .\assets\logo\Updater.ico -n "March7th Updater" --exclude-module numpy --exclude-module pandas updater.py -y

      # 步骤5：移动资源到dist目录
      - name: Move assets to dist directory
        run: |
          Copy-Item -Path ".\dist\March7th Assistant\*" -Destination ".\dist\March7thAssistant\" -Recurse -Force
          Copy-Item -Path ".\dist\March7th Launcher\*" -Destination ".\dist\March7thAssistant\" -Recurse -Force
          Copy-Item -Path ".\assets\" -Destination ".\dist\March7thAssistant\assets\" -Recurse -Force
          Copy-Item -Path ".\README.md" -Destination ".\dist\March7thAssistant\" -Force

      # 步骤6：创建压缩包
      - name: Create archive
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # Compress-Archive -Path .\dist\March7thAssistant\ -DestinationPath .\dist\March7thAssistant.zip -Force
          .\assets\binary\7za.exe a -tzip .\dist\March7thAssistant.zip .\dist\March7thAssistant\
          .\assets\binary\7za.exe a -t7z .\dist\March7thAssistant.7z .\dist\March7thAssistant\

      # 步骤7：移动第三方库到dist目录
      - name: Move 3rdparty to dist directory
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          python build.py github-actions
          Copy-Item -Path .\3rdparty\ -Destination .\dist\March7thAssistant\3rdparty\ -Recurse -Force
          Rename-Item -Path .\dist\March7thAssistant -NewName March7thAssistant_full

      # 步骤8：创建完整的压缩包
      - name: Create full zip archive
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # Compress-Archive -Path .\dist\March7thAssistant_full\ -DestinationPath .\dist\March7thAssistant_full.zip -Force
          .\assets\binary\7za.exe a -tzip .\dist\March7thAssistant_full.zip .\dist\March7thAssistant_full\
          .\assets\binary\7za.exe a -t7z .\dist\March7thAssistant_full.7z .\dist\March7thAssistant_full\

      

      # 步骤8.2：对比文件，生成增量包和 removefile.txt
      - name: Generate patch package and removefile.txt
        if: startsWith(github.ref, 'refs/tags/') && hashFiles('./dist/prev_release/March7thAssistant_full.zip') != ''
        shell: pwsh
        run: |
          $old = Get-ChildItem -Path ./dist/prev_release/unzip/March7thAssistant_full -Recurse | Where-Object {!$_.PSIsContainer}
          $new = Get-ChildItem -Path ./dist/March7thAssistant_full -Recurse | Where-Object {!$_.PSIsContainer}
          $oldHash = @{}
          foreach ($f in $old) {
            $rel = $f.FullName.Substring((Resolve-Path ./dist/prev_release/unzip/March7thAssistant_full).Path.Length+1)
            $oldHash[$rel] = (Get-FileHash $f.FullName -Algorithm SHA256).Hash
          }
          $newHash = @{}
          foreach ($f in $new) {
            $rel = $f.FullName.Substring((Resolve-Path ./dist/March7thAssistant_full).Path.Length+1)
            $newHash[$rel] = (Get-FileHash $f.FullName -Algorithm SHA256).Hash
          }
          $changed = @()
          foreach ($k in $newHash.Keys) {
            if (-not $oldHash.ContainsKey($k) -or $oldHash[$k] -ne $newHash[$k]) {
              $changed += $k
            }
          }
          $removed = @()
          foreach ($k in $oldHash.Keys) {
            if (-not $newHash.ContainsKey($k)) {
              $removed += $k
            }
          }
          # 复制变更文件到patch目录
          $patchDir = "./dist/March7thAssistant_patch_${{ env.PREV_TAG }}_to_${{ env.CUR_TAG }}"
          mkdir $patchDir -Force | Out-Null
          foreach ($f in $changed) {
            $src = Join-Path (Resolve-Path ./dist/March7thAssistant_full).Path $f
            $dst = Join-Path $patchDir $f
            mkdir (Split-Path $dst) -Force | Out-Null
            Copy-Item $src $dst -Force
          }
          # 写入removefile.txt
          $removed | Out-File -Encoding utf8 "$patchDir/removefile.txt"

      # 步骤8.3：打包增量包
      - name: Create patch zip archive
        if: startsWith(github.ref, 'refs/tags/') && steps.prev_release.outputs.url != ''
        env:
          PREV_TAG: ${{ steps.prev_release.outputs.tag }}
          CUR_TAG: ${{ github.ref_name }}
        run: |
          $patchZip = "March7thAssistant_patch_${env:PREV_TAG}_to_${env:CUR_TAG}.zip"
          $patch7z = "March7thAssistant_patch_${env:PREV_TAG}_to_${env:CUR_TAG}.7z"
          .\assets\binary\7za.exe a -tzip ".\dist\$patchZip" .\dist\March7thAssistant_patch_${{ env.PREV_TAG }}_to_${{ env.CUR_TAG }}\
          .\assets\binary\7za.exe a -t7z ".\dist\$patch7z" .\dist\March7thAssistant_patch_${{ env.PREV_TAG }}_to_${{ env.CUR_TAG }}\

      # 步骤9：创建GitHub发布
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          PREV_TAG: ${{ steps.prev_release.outputs.tag }}
          CUR_TAG: ${{ github.ref_name }}
        with:
          name: March7thAssistant ${{ github.ref_name }}
          files: |
            ./dist/March7thAssistant_full.zip
            ./dist/March7thAssistant.zip
            ./dist/March7thAssistant_full.7z
            ./dist/March7thAssistant.7z
            ./dist/March7thAssistant_patch_${{ env.PREV_TAG }}_to_${{ env.CUR_TAG }}.zip
            ./dist/March7thAssistant_patch_${{ env.PREV_TAG }}_to_${{ env.CUR_TAG }}.7z
          prerelease: false

      # 步骤10：强制触发 MirrorChyan 上传
      - name: Trigger MirrorChyanUploading
        if: github.repository == 'moesnow/March7thAssistant'
        shell: bash
        run: |
          gh workflow run --repo $GITHUB_REPOSITORY 'MirrorChyan Uploading'
          gh workflow run --repo $GITHUB_REPOSITORY 'MirrorChyan Release Note'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
